// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VijayAnand.XFormsTemplates
{
    internal sealed partial class Vsix
    {
        public const string Id = "XFormsTemplates.2924dcc2-7ffd-4b48-8828-c830a2fab6e0";
        public const string Name = "Xamarin.Forms Project and Item Templates";
        public const string Description = @"Xamarin.Forms Project and Item Templates for building native apps for iOS, Android, UWP, macOS, Tizen from a single, shared C# codebase.";
        public const string Language = "en-US";
        public const string Version = "1.0.0.0";
        public const string Author = "Vijay Anand E G";
        public const string Tags = "Xamarin.Forms, Mobile, iOS, Android, UWP, Desktop, Windows, Templates, Shell, Library, Visual Studio, Resource Dictionary, Xamarin, macOS, Tizen";
    }
}
